export const Konosuba = [
	{
		id: 'a5b0851b-9e8e-4c82-bc2a-5ba17842dab8',
		name: '"Crimson Demon" Megumin',
		series: 'KS/W49',
		cardID: 'KS/W49-034',
		rarity: 'RR',
		color: 'Red',
		side: 'Weiss',
		type: 'Charicter',
		level: 3,
		power: '9500',
		cost: 2,
		soul: 2,
		trait1: '冒険者 (Adventurer)',
		trait2: '魔法 (Magic)',
		triggers: 'soul',
		cardText: `[A] When this is placed from hand to the Stage, put the top card of your Library in the Waiting Room, and choose up to 1 of your Opponent's Level X or lower Characters and put it in the Waiting Room. X = the Level of that card. (Climax cards are considered Level 0 for this effect)
		[A] CX COMBO [Discard a card from your hand to the Waiting Room] At the start of your Encore Step, if "Explosion Magic" is in your Climax Zone, you have another '"Full of Concerns" Kazuma', and this is in the Front Row, you may pay cost. If so, deal 5 Damage to your Opponent. (Damage Cancel can occur) `,
		link: 'https://heartofthecards.com/code/cardlist.html?card=WS_KS/W49-034',
		image: 'https://heartofthecards.com/images/cards/ws/ks-w49-034.gif'
	},
	{
		id: 'b5b0851b-9e8e-4c82-bc2a-5ba17842dab8',
		name: 'Explosion Magic',
		series: 'KS/W49',
		cardID: 'KS/W49-069',
		rarity: 'CC',
		color: 'Red',
		side: 'Weiss',
		type: 'Climax',
		level: 0,
		power: 0,
		cost: 0,
		soul: 0,
		trait1: null,
		trait2: null,
		triggers: 'salvage',
		cardText: `[C] All your Characters gain +1000 Power and +1 Soul. `,
		link: 'https://heartofthecards.com/code/cardlist.html?card=WS_KS/W49-069',
		image: 'https://heartofthecards.com/images/cards/ws/ks-w49-069.gif'
	},
	{
		id: 'c5b0851b-9e8e-4c82-bc2a-5ba17842dab8',
		name: 'Explosion Magic Everyday!',
		series: 'KS/W49',
		cardID: 'KS/W49-064',
		rarity: 'U',
		color: 'Red',
		side: 'Weiss',
		type: 'Event',
		level: 1,
		power: 0,
		cost: 1,
		soul: 0,
		trait1: null,
		trait2: null,
		triggers: null,
		cardText: `If you are Level 2 or lower and your Opponent is Level 1 or lower, you may discard a ::Magic:: Character card from your hand to the Waiting Room. If so, put this in your Level Zone, and perform the following action 6 times. "Deal 1 Damage to your Opponent." (Damage Cancel can occur) `,
		link: 'https://heartofthecards.com/code/cardlist.html?card=WS_KS/W49-064',
		image: 'https://heartofthecards.com/images/cards/ws/ks-w49-064.gif'
	}
];